/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateParentCategoryArgs } from "./CreateParentCategoryArgs";
import { UpdateParentCategoryArgs } from "./UpdateParentCategoryArgs";
import { DeleteParentCategoryArgs } from "./DeleteParentCategoryArgs";
import { ParentCategoryFindManyArgs } from "./ParentCategoryFindManyArgs";
import { ParentCategoryFindUniqueArgs } from "./ParentCategoryFindUniqueArgs";
import { ParentCategory } from "./ParentCategory";
import { CategoryFindManyArgs } from "../../category/base/CategoryFindManyArgs";
import { Category } from "../../category/base/Category";
import { ParentCategoryService } from "../parentCategory.service";

@graphql.Resolver(() => ParentCategory)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class ParentCategoryResolverBase {
  constructor(
    protected readonly service: ParentCategoryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ParentCategory",
    action: "read",
    possession: "any",
  })
  async _parentCategoriesMeta(
    @graphql.Args() args: ParentCategoryFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [ParentCategory])
  @nestAccessControl.UseRoles({
    resource: "ParentCategory",
    action: "read",
    possession: "any",
  })
  async parentCategories(
    @graphql.Args() args: ParentCategoryFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ParentCategory[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "ParentCategory",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => ParentCategory, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ParentCategory",
    action: "read",
    possession: "own",
  })
  async parentCategory(
    @graphql.Args() args: ParentCategoryFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ParentCategory | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "ParentCategory",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => ParentCategory)
  @nestAccessControl.UseRoles({
    resource: "ParentCategory",
    action: "create",
    possession: "any",
  })
  async createParentCategory(
    @graphql.Args() args: CreateParentCategoryArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ParentCategory> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "ParentCategory",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"ParentCategory"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => ParentCategory)
  @nestAccessControl.UseRoles({
    resource: "ParentCategory",
    action: "update",
    possession: "any",
  })
  async updateParentCategory(
    @graphql.Args() args: UpdateParentCategoryArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ParentCategory | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "ParentCategory",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"ParentCategory"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ParentCategory)
  @nestAccessControl.UseRoles({
    resource: "ParentCategory",
    action: "delete",
    possession: "any",
  })
  async deleteParentCategory(
    @graphql.Args() args: DeleteParentCategoryArgs
  ): Promise<ParentCategory | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Category])
  @nestAccessControl.UseRoles({
    resource: "ParentCategory",
    action: "read",
    possession: "any",
  })
  async childrens(
    @graphql.Parent() parent: ParentCategory,
    @graphql.Args() args: CategoryFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Category[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Category",
    });
    const results = await this.service.findChildrens(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }
}
